### ISSUE TITLE
QA Issues

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [Makewebbetter/invoice-system-for-woocommerce#57]
Woo Commerce Version - 5.9.0
WordPress Version - 5.8.2
Plugin Version - 1.0.5
Description -
DOC:
https://docs.google.com/document/d/1vLrllxLRZLK9UYkQmxxUi3f4RaH4qyTTsRoM0XVKDAY/edit?usp=sharing

**Comment by vivekkushwaha-cedcoss** [comment]
issues fixed

**Comment by Sukirti-CEDCOSS** [comment]
Verified
