### ISSUE TITLE
The PDF should open to the new tab

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [Makewebbetter/invoice-system-for-woocommerce#58]
Wordpress: 5.8.2
Woocommerce: 5.9.0
Version: 1.0.5
Description: 
The PDF should open to the new tab. This is happening when we are opening the pdf from my account-->orders 
https://www.awesomescreenshot.com/video/6360915?key=dd78450d911a0c9bc7c30a4af861c861

**Comment by rishabhmwb** [comment]
resolved

**Comment by Sukirti-CEDCOSS** [comment]
verified
