### ISSUE TITLE
The downloading of PDF from the admin panel is producing an error.

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [Makewebbetter/invoice-system-for-woocommerce#59]
Wordpress: 5.8.2
Woocommerce: 5.9.0
Version: 1.0.5
Description:
The downloading of PDF from the admin panel is producing an error.
![image](https://user-images.githubusercontent.com/85384857/145387974-a6eb28d4-6aa6-4ad5-865f-8c48fbc4cd93.png)
![image](https://user-images.githubusercontent.com/85384857/145388071-8147fcb1-785e-4f9e-998d-c26b4b24904e.png)

**Comment by rishabhmwb** [comment]
resolved

**Comment by Sukirti-CEDCOSS** [comment]
verified
